### ISSUE TITLE
/start.sh doesn't work on apple silicon

### ISSUE THREAD

**Issue by mrinaldutta1** [confluentinc/training-fundamentals-src#20]
fails with error 

`ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by g-donev** [comment]
same here

**Comment by fkojevnikov** [comment]
quick fix:
to the .yml files add the following
'''
platform: linux/x86_64
'''

**Comment by ness-balasubramanianramachandran** [comment]
Any progress on this error and moreover am not sure where to use the quick fix

**Comment by fkojevnikov** [comment]
There are 4 x docker-compose.yml files.
Under "image: confluentinc/cp-zookeeper:7.1.1-1-ubi8"
Insert the line "platform: linux/x86_64"

**Comment by jlieow** [comment]
@ness-balasubramanianramachandran I faced the same issue but unfortunately this cannot be resolved unless confluent updates their images. 

Whilst the images `confluentinc/cp-zookeeper` and `confluentinc/cp-server` has images that support the `linux/arm64` platform, and the docker-compose.yml can be updated as such to pull the `arm64` variants:
```
version: "3.5"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.1.2-1-ubi8
        platform: linux/arm64
        restart: always
        hostname: zookeeper
        networks:
            - confluent
        ports:
            - 2181:2181
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-server:7.1.2-1-ubi8
        platform: linux/arm64
        restart: always
        hostname: kafka
        networks:
            - confluent
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 101
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_LOG_RETENTION_HOURS: 1
            KAFKA_LOG_SEGMENT_BYTES: 536870912
            KAFKA_LOG_RETENTION_BYTES: 536870912
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka:9092"
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1

networks:
    confluent:
```

The image `cnfltraining/vp-producer` does not have any `linux/arm64` variant and the latest update to this image is over 4 years ago.
```
docker container run -d \
    --name producer \
    --net exploring_confluent \
    cnfltraining/vp-producer:v2 
```
